version: "2.2"
# ipv6 is not supported in version 3

services:
  tic-tac-toe:
    restart: unless-stopped
    image: ubuntu
    init: true
    build: tic-tac-toe
    ports:
        - "3333:1337"


networks:
  default:
    enable_ipv6: true
    ipam:
        driver: default
        config:
            - subnet: "fd42:d0ce:1111::/64"
